
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'BEGIN DIRseq : BEGINseq : seq instrinstr : DIR'
    
_lr_action_items = {'BEGIN':([0,],[2,]),'$end':([1,2,3,4,],[0,-1,-2,-3,]),'DIR':([1,2,3,4,],[4,-1,-2,-3,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'seq':([0,],[1,]),'instr':([1,],[3,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> seq","S'",1,None,None,None),
  ('seq -> BEGIN','seq',1,'p_seq_b','lab7.py',21),
  ('seq -> seq instr','seq',2,'p_seq_instr','lab7.py',25),
  ('instr -> DIR','instr',1,'p_instr_dir','lab7.py',30),
]
